workspace:
  base: /go
  path: src/github.com/magento-mcom/go-common

pipeline:
  dep:
    image: mcom/gobuilder:1.10
    pull: true
    commands:
      - "make dep"

  lint:
    image: golangci/golangci-lint:v1.16.0
    pull: true
    commands:
      - "make lint"

  test-1-10:
    group: test
    image: mcom/gobuilder:1.10
    pull: true
    commands:
      - "make test"

  test-1-11:
    group: test
    image: mcom/gobuilder:1.11
    pull: true
    commands:
      - "make test"

  test-1-12:
    group: test
    image: mcom/gobuilder:1.12
    pull: true
    commands:
      - "make test"

  coverage-report:
    group: publish
    image: mcom/go-coverage-persistor:latest
    pull: true
    environment:
      COVER_FILE: "coverage.out"
      COVER_DEBUG: "1"
      COVER_REPORT_UPDATE: "replace"
    when:
      event: [ pull_request, push ]
    secrets:
      - { source: github_token, target: github_token }
      - { source: coverage_es_user, target: es_user }
      - { source: coverage_es_password, target: es_password }
      - { source: coverage_es_url, target: es_url }
