workspace:
  base: /go
  path: src/github.com/magento-mcom/go-common

pipeline:
  dep:
    image: mcom/gobuilder:1.9
    pull: true
    commands:
      - "make dep"

  lint:
    image: golangci/golangci-lint:v1.16.0
    pull: true
    commands:
      - "make lint"

  test-1-9:
    group: test
    image: mcom/gobuilder:1.9
    pull: true
    commands:
      - "make test"

  test-1-10:
    group: test
    image: mcom/gobuilder:1.10
    pull: true
    commands:
      - "make test"

  test-1-11:
    group: test
    image: mcom/gobuilder:1.11
    pull: true
    commands:
      - "make test"

  test-1-12:
    group: test
    image: mcom/gobuilder:1.12
    pull: true
    commands:
      - "make test"

  coverage:
    group: coverage
    image: mcom/gobuilder:1.12
    pull: true
    commands:
      - "go get github.com/ory/go-acc"
      - "go-acc ./... > coverage.out"
      - "cat coverage.out"

  coverage-persistor:
    group: publish
    image: mcom/go-coverage-persistor:latest
    pull: true
    environment:
      COVER_FILE: "coverage.out"
    when:
      event: pull_request
    secrets: [ GITHUB_TOKEN ]
